<a href="https://colab.research.google.com/github/E1250/ZTM-Courses/blob/main/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)
# Done

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

# Create random tensor
rand1 = torch.rand(7,7)
rand1

tensor([[0.5840, 0.1368, 0.9391, 0.1950, 0.1429, 0.5082, 0.5082],
        [0.8374, 0.4118, 0.4584, 0.5190, 0.3355, 0.8380, 0.6347],
        [0.2253, 0.7514, 0.4923, 0.1510, 0.9682, 0.6359, 0.2045],
        [0.2273, 0.1577, 0.3495, 0.4917, 0.6954, 0.5150, 0.6671],
        [0.0500, 0.9532, 0.5281, 0.2964, 0.8496, 0.0836, 0.0926],
        [0.6439, 0.6864, 0.4794, 0.2156, 0.0619, 0.0156, 0.7019],
        [0.5444, 0.0847, 0.6211, 0.0615, 0.8731, 0.8510, 0.4180]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [11]:
# Create another random tensor
rand2 = torch.rand(1,7)
# Perform matrix multiplication 
torch.matmul(rand1,rand2.reshape(7,-1))

tensor([[1.5758],
        [2.1964],
        [2.4219],
        [1.6230],
        [2.1140],
        [1.5831],
        [2.1649]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [15]:
# Set manual seed
torch.manual_seed(seed=0)

# Create two random tensors
rand1_tensor = torch.rand(7,7)
rand2_tensor = torch.rand(1,7)

# Matrix multiply tensors
torch.mm(rand1_tensor,rand2_tensor.reshape(7,1)) # anoher way to matrix mul is using mm

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [18]:
# Set random seed on the GPU

torch.cuda.manual_seed(seed=1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [21]:
# Set random seed
torch.manual_seed(seed=1234)

rand1_tensor = torch.rand(2,3)
rand2_tensor = torch.rand(2,3)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available else 'cpu'
is_exist = torch.cuda.is_available

# Create two random tensors on GPU
with torch.cuda.device(0): # `0` is index of gpu you select
  rand1_tensor = torch.rand(2,3).cuda()
  rand2_tensor = torch.rand(2,3).to('cuda')  # you can use 'device' variable


rand1_tensor,rand2_tensor


(tensor([[0.7749, 0.8208, 0.2793],
         [0.6817, 0.2837, 0.6567]], device='cuda:0'),
 tensor([[0.2388, 0.7313, 0.6012],
         [0.3043, 0.2548, 0.6294]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [24]:
# Perform matmul on tensor_A and tensor_B
out = rand1_tensor.matmul(rand2_tensor.reshape(3,2))

### 8. Find the maximum and minimum values of the output of 7.

In [28]:
# Find max
print(out.max())
# Find min
print(out.min())

tensor(0.9982, device='cuda:0')
tensor(0.5006, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [29]:
# Find arg max
print(out.argmax())

# Find arg min
print(out.argmin())


tensor(3, device='cuda:0')
tensor(2, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [31]:
# Set seed
torch.manual_seed(seed=7)

# Create random tensor
rand1 = torch.rand(1,1,1,10)
ones = torch.ones(1,1,1,10)

# Remove single dimensions  
ones.squeeze_()  # the `_` in the end of the function for inplace changement

# Print out tensors and their shapes
print(f'{rand1} , shape = {rand1.shape}')
print(f'{rand2} , shape = {rand2.shape}')


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) , shape = torch.Size([1, 1, 1, 10])
tensor([[0.7810, 0.8988, 0.5323, 0.2026, 0.9693, 0.4895, 0.1379]]) , shape = torch.Size([1, 7])
